word_list=[
    ("develop the theory of relativity", "发展了相对论"),
    ("be good at writing music pieces", "擅长写曲子"),
    ("make sb. feel less stressed", "使某人觉得压力更小"),
    ("get refreshed", "恢复精神，恢复活力"),
    ("energy", "n.能量"),
    ("energetic", "adj.精力充沛的"),
    ("call on sb. to do sth.", "呼吁/号召某人做某事"),
    ("call on sb.", "拜访某人"),
    ("call at sp.", "拜访某地"),
    ("subscribe", "v.关注，订阅"),
    ("recommend", "v.推荐"),
    ("recommendation", "n.推荐"),
    ("one of the greatest songs of all time", "有史以来最伟大的歌曲之一"),
    ("offer", "v.主动提出"),
    ("offer sb. sth./offer sth. to sb.", "主动提供某物给某人"),
    ("offer to do sth.", "主动提出做某事"),
    ("What‘s more/In addition/Additionally/Furthermore/Besides", "此外，另外"),
    ("be widely used in many sports events", "在许多体育赛事中被广泛使用（be used被动语态）"),
    ("team spirit", "团队精神"),
    ("encourage the athletes", "鼓励运动员"),
    ("athlete", "n.运动员"),
    ("athletic", "adj.运动的，有运动才能的，健壮的"),
    ("comfort zone", "舒适圈"),
    ("pursue one’s dream", "追寻某人的梦想"),
    ("by oneself/on one’s own", "自己做"),
    ("once/twice/three times", "一次/两次/三次，使用现在完成时"),
    ("I have been to Beijing twice.", "我去过北京两次。"),
    ("cover v.覆盖 n.封面，盖子-discover", "v.发现-discovery n."),
    ("have a tough childhood", "度过一个艰难的童年"),
    ("be famous as/be known as", "作为……而闻名"),
    ("be famous for/be known for", "因为……而闻名"),
    ("make a living", "谋生"),
    ("instruction", "n.指示，用法说明"),
    ("a fighter for women’s rights", "女权战士"),
    ("right", "n.权利")
]