word_list = [
    ("在(足球/篮球)队", "on the (football/basketball) team"),
    ("在农场", "on the farm"),
    ("在夏令营", "on the summer camp"),
    ("n.课程", "course"),
    ("adj.紧张的", "nervous"),
    ("adj.焦虑的", "anxious"),
    ("adj.有压力的", "stressed"),
    ("回应某人的请求", "respond to one's request"),
    ("n.回答", "response"),
    ("v.回应", "respond"),
    ("邀请某人做某事", "invite sb. to do sth."),
    ("conj.因为，既然；自从", "since"),
    ("又，再一，另一", "another"),
    ("一个...另一个...（共两个）", "one ... the other ..."),
    ("other + n.复 （无范围）", "others"),
    ("the other + n.复 （有范围）", "the others"),
    ("一些...另一些...", "some ... others ..."),
    ("建议（某人）做某事", "advise sb. (to do/doing) sth."),
    ("非此即彼两者择一二者择一二选一", "either ... or ..."),
    ("既不 …… 也不 ……", "neither ... nor ..."),
    ("不但 …… 而且 ……", "not only ... but also ..."),
    ("看着某人的眼睛", "look at sb. in one's eyes"),
    ("第一个挑战是各种各样的口音，这让我们很难理解。", "The first challenge was the variety of accents, which made it diffcuit for us to understand."),
    ("adj.明显的", "obvious"),
    ("v.改变", "change"),
    ("n.（多种）误会（可数）；（一种）误会（不可数）；", "misunderstanding"),
    ("n.多样性（不可数）；n.种类（可数）", "variety"),
    ("n.设备，器材（不可数）", "equipment"),
    ("希望做某事", "wish to do"),
    ("n.知识", "knowledge"),
    ("adj.有见识的", "knowledgeable"),
    ("n.改变", "change"),
    ("adj.可改变的", "changeable"),
    ("临近", "approach/be near/be around the corner"),
    ("我认为贝蒂在我们班笑得最甜。", "I think Betty smiles (the) most sweetly in our class."),
    ("由于演出（即将/即将/临近/即将），我们集中精力在大厅里练习。", "As the performance (is coming/is coming up/is near/approaches/is around the corner), we focus on practicing in the hall."),
    ("我们还能做些什么来帮助青少年在夏令营中了解彼此呢？", "What else can we do to help the teenagers know about each other at the summer camp?")

]