word_list=[
    ("位居票房榜首", "top the box office"),
    ("使某人惊讶/高兴", "blow sb. away"),
    ("大打出手，互殴", "come to blows"),
    ("接受他们的不同", "accept their differences"),
    ("并肩作战", "fight side by side"),
    ("v.奋斗，挣扎", "struggle"),
    ("背弃/疏远你的朋友", "turn your back on your friend"),
    ("交流的方式", "ways of communication/ways to communicate"),
    ("一种做某事的方式", "a way to do/a way of doing"),
    ("与……交流", "communicate with"),
    ("在学生中进行一项调查", "do a survey among students"),
    ("在学生中实施一项调查", "conduct a survey among students"),
    ("在学生中完成一项调查", "carry out a survey among students"),
    ("亲自", "in person"),
    ("n.人-adj.个人的-adv.就个人而言-n.性格", "person-personal-personally-personality"),
    ("v.发短信", "text"),
    ("社交媒体", "social media"),
    ("adj.社交的-n.社会", "social-society"),
    ("n.媒介，手段（单数）adj.中等的，中间的，五分熟的", "medium"),
    ("n.媒介（复数）", "media"),
    ("视频聊天", "video-chatting"),
    ("v.闲聊-闲聊（过去式）-闲聊（过去分词）-闲聊（进行时）", "chat-chatted-chatted-chatting"),
    ("与某人闲聊", "chat with sb."),
    ("与某人通过电话交谈(on the phone)", "talk with sb. on the phone/talk to sb. on the phone"),
    ("与某人通过电话交谈(by phone)", "talk to sb. by phone/talk with sb. by phone"),
    ("基于一项涉及超过500名学生的调查", "be based on a survey of 500 students"),
    ("参加活动（the survey/a sports meeting...）", "take part in/join in"),
    ("加入组织（the army/a singing group/a club）", "join"),
    ("在……中受欢迎", "be popular with/be popular among"),
    ("v.允许", "allow"),
    ("n.津贴，补贴", "allowance"),
    ("允许某人做某事", "allow sb. to do"),
    ("某人被允许做某事", "sb. be allowed to do"),
    ("将某人的想法写在纸上", "put one's thoughts on paper"),
    ("一遍遍地读", "read sth. over and over again"),
    ("得到即时关注", "get immediate attention"),
    ("adj.即时的", "immediate"),
    ("adv.立即", "immediately"),
    ("在屏幕上看见彼此", "see each other on the screen"),
    ("adj.省时的", "time-saving"),
    ("更清晰地表达她的观点", "express her feelings more clearly"),
    ("顺便拜访", "drop by"),
    ("设法保持联系", "manage to stay in touch/manage to keep in touch")
]