word_list = [
    ("adj.流畅的，流利的", "fluent"),
    ("adv.流利地", "fluently"),
    ("n.流利，流畅", "fluency"),
    ("n.沟通者，交流者", "communicator"),
    ("礼貌地说话", "speak politely"),
    ("专注于", "focus on/concentrate on"),
    ("跟上", "keep up"),
    ("男生发现很难跟上。（it作形式宾语）", "The boys found it hard to keep up."),
    ("担心这种情况", "worry about the situation"),
    ("谁为当前的情况负责？", "Who is responsible for the current situation?"),
    ("n.情况", "situation"),
    ("对某人喊叫", "shout (to/at) sb."),
    ("v.后悔；遗憾(过去式-过去分词)", "regret-regretted-regretted"),
    ("adj.后悔的，遗憾的", "regretful"),
    ("遗憾未做", "regret to do"),
    ("后悔做了", "regret doing"),
    ("我后悔没有为这次考试更努力学习。", "I regret not studying harder for the exam."),
    ("我们很遗憾地通知你，这次春游被取消了。", "We regret to inform you that the spring outing has been canceled."),
    ("最终", "in the end/finally/at last/eventually"),
    ("有效的沟通/交流", "effective communication"),
    ("adj.有效的", "effective"),
    ("n.效果", "effect"),
    ("v.影响", "affect"),
    ("adv.有效地", "effectively"),
    ("v.n.拥抱(过去式-过去分词)", "hug-hugged-hugged"),
    ("把A连接到B", "connect A (to/with) B"),
    ("打折", "be on sale"),
    ("出售", "be for sale"),
    ("v.卖(过去式-过去分词)", "sell-sold-sold"),
    ("n.销售", "sale"),
    ("天气放晴，解决问题", "clear up"),
    ("时不时（一般现在时的标志）", "from time to time/at times/now and then/now and again"),
    ("选择合适的话题可以在交流中避免尴尬。", "He gained confidence and found the courage to sing solo in public."),
    ("中国比非洲任何一个国家都大。（中国不属于非洲）", "China is bigger than any country in Africa."),
    ("中国比亚洲任何一个其他国家都大。（中国属于亚洲，other排除自身）", "China is bigger than any other country in Asia."),
    ("我没有弗兰克高。", "I am not as tall as Frank./I am less tall than Frank./Frank is taller than I."),
    ("眼见为实", "Seeing is believing.")
]