word_list=[
    ("交流/沟通技能", "communication skills"),
    ("发表一个关于……的演讲", "(give/make/deliver) a speech (about/on) sth."),
    ("v. 谈话，交谈(过去式-过去分词)", "speak-spoke-spoken"),
    ("n. 演说，发言，谈话；(复数)", "speech-speeches"),
    ("一次在一个国际夏令营的经历", "an experience at an international summer camp"),
    ("跨越文化差异", "cross the cultural divide"),
    ("v.穿过，跨越 n.十字，叉", "cross"),
    ("prep.穿过", "across"),
    ("n.文化", "culture"),
    ("adj.文化的", "cultural"),
    ("互相理解", "understand (each other/one another)"),
    ("说英语/法语/德语/汉语", "speak (English/French/German/Chinese)"),
    ("用英语说", "say it in English"),
    ("被最广泛使用的语言之一", "one of the most widely used languages"),
    ("各种口音", "the variety of accents"),
    ("v.使……不同", "vary"),
    ("adj.各种各样的", "various/a variety of/varieties of"),
    ("n.种类", "variety"),
    ("图书馆里有各种各样的书。", "There are (a variety of books/varieties of books/various books) in the library."),
    ("此外，另外", "in addition/additionally/furthermore/what's more/besides/moreover"),
    ("导致误会", "(cause/lead to) misunderstandings"),
    ("v.意识到，实现", "realise/realize"),
    ("adj.真正的", "real"),
    ("n. 认识，领悟", "realization/realisation"),
    ("被用来消除不同文化之间的隔阂", "be used to bridge the gap between different cultures"),
    ("v.在……上架桥", "bridge"),
    ("消除……的隔阂", "bridge the gap between"),
    ("展示给某人如何做某事", "show sb. how to do sth."),
    ("教某人如何做某事", "teach sb. how to do sth."),
    ("用一只手进行手指计数", "do finger counting with one hand"),
    ("对……感兴趣", "be interested in doing sth."),
    ("热衷于……", "(be keen on/be fond of) doing sth."),
    ("汉字在历史上的变化", "changes of Chinese characters through history"),
    ("读（发音）一些汉字", "pronounce some Chinese characters"),
    ("字母系统", "alphabet system"),
    ("按字母顺序", "in alphabetical order"),
    ("我们经常使用的手势", "gestures (that/which) we often use"),
    ("令某人非常高兴/惊讶/失望/尴尬的是……", "much to one's (pleasure/surprise/disappointment/embarrassment)"),
    ("忘记这次经历", "forget this experience"),
    ("v. 忘记，遗忘；(过去式-过去分词)", "forget-forgot-forgotten"),
    ("adj.健忘的", "forgetful"),
    ("adj.容易忘记的", "forgettable"),
    ("adj.难忘的", "unforgettable"),
    ("一个向世界介绍我们文化的好机会", "a good chance to introduce our culture to the world"),
    ("做某事的好机会；", "a good chance to do sth."),
    ("把A介绍给B认识", "introduce A to B"),
    ("adj.有效的", "effective "),
    ("adv. 有效地；实际上", "effectively"),
    ("倾听彼此", "listen to each other")
]