word_list = [
    ("v.打击", "stroke"),
    ("n.中暑", "heatstroke"),
    ("n.窒息", "choking"),
    ("心脏病", "heart attack"),
    ("做调查", "(do/conduct/carry out) a survey"),
    ("避免做某事", "avoid doing sth."),
    ("n.难堪", "embarrassment"),
    ("v.聊天（过去式，过去分词）", "chat-chatted-chatted"),
    ("适合某人", "be suitable for sb."),
    ("允许某人做某事", "allow sb. to do sth."),
    ("棕榈树", "palm tree"),
    ("提出要求", "make a request"),
    ("v.展示", "present"),
    ("v.发音", "pronounce"),
    ("n.发言", "pronouncation"),
    ("n.建议", "advice"),
    ("v.发明", "invent"),
    ("n.发明物", "invention"),
    ("n.发明家", "inventor"),
    ("Let's 反义疑问句", "shall we?"),
    ("Let us 反义疑问句", "will you?"),
    ("突然间", "all of a sudden/suddenly"),
    ("你能告诉我图书馆在哪儿吗?", "Can you tell me where the library is?"),
    ("肺", "lung"),
    ("撑过去", "make it"),
    ("v.点亮", "brighten"),
    ("与某人玩游戏", "play games with sb."),
    ("捉弄某人", "play tricks on sb.")
]