word_list = [
    ("浏览；查看", "look through"),
    ("每天的；日常的", "everyday"),
    ("重建；重塑", "rebuild"),
    ("香烟", "cigarette"),
    ("阻止；预防", "prevent"),
    ("给...留下深刻的好印象", "impress"),
    ("钥匙", "key"),
    ("落下；掉落", "drop"),
    ("钱包", "wallet"),
    ("比赛", "contest"),
    ("弄不懂；困惑", "lost"),
    ("架子；隔板", "shelf"),
    ("图书管理员", "librarian"),
    ("借阅；查看", "check out"),
    ("紧急情况", "emergency"),
    ("仁慈", "kindness"),
    ("通常的", "usual"),
    ("像往常一样；照例", "as usual"),
    ("邻居", "neighbour"),
    ("突然的", "sudden"),
    ("突然地；突然", "suddenly"),
    ("攻击；发作；侵袭", "attack"),
    ("苍白的", "pale"),
    ("汗水", "sweat"),
    ("震惊", "shock"),
    ("使震惊；使惊讶", "shock"),
    ("使平静；使镇静", "calm"),
    ("他自己", "himself"),
    ("没有人", "nobody"),
    ("女士", "lady"),
    ("很快地", "quickly"),
    ("操作员", "operator"),
    ("清楚地", "clearly"),
    ("救护车", "ambulance"),
    ("药丸", "pill"),
    ("帮助；援助", "aid"),
    ("一次", "once"),
    ("立刻；马上", "at once"),
    ("点头", "nod"),
    ("感激", "thankful"),
    ("感激的、表示感激的", "grateful")
]