word_list = [
    ("每日英雄", "everyday heroes"),
    ("adj.每天的", "everyday"),
    ("我每天都在图书馆学习。", "I study in the library every day."),
    ("浏览，查看", "look through"),
    ("看着", "look at"),
    ("寻找", "look for"),
    ("照顾", "look after"),
    ("查阅", "look up"),
    ("调查", "look into/investigate"),
    ("看不清，轻视", "look down (on/upon)"),
    ("小心", "look out/watch out"),
    ("帮助生病的人", "help out sick people"),
    ("留了三年头发", "save her hair for three years"),
    ("v.捐献，捐赠", "donate"),
    ("n.捐献，捐赠", "donation"),
    ("捐赠某物给某人", "donate sth. to sb."),
    ("向慈善机构捐款", "donate money to a charity"),
    ("n.志愿者；v.志愿做", "volunteer"),
    ("adj.志愿的", "voluntary"),
    ("志愿做某事", "volunteer to do"),
    ("志愿工作", "voluntary work"),
    ("分发食物给某人", "hand out food to sb."),
    ("独居老人", "the elderly who live alone"),
    ("adj.上了年纪的", "elderly"),
    ("adj.年长的(强调辈分)", "elder"),
    ("哥哥/姐姐", "elder (brother/sister)"),
    ("adj.较老的(强调年龄)", "older"),
    ("有需要的人", "people in need"),
    ("患难见真情。", "A friend in need is a friend indeed."),
    ("帮助某人重建信心", "help sb. (to) rebuild confidence"),
    ("帮助某人(做/做/用)某事", "help sb. (do/to do/with) sth."),
    ("鼓励某人(不要/永远不要)放弃希望", "encourage sb. (not/never) to give up hope"),
    ("捡起香烟头", "pick up cigarette ends"),
    ("点一支烟", "light a cigarette"),
    ("防止火灾", "prevent fires"),
    ("v.防止，预防", "prevent"),
    ("n.预防", "prevention"),
    ("阻止某人做某事", "(prevent/keep/stop) sb. from doing sth."),
    ("一则/四则新闻", "(a piece/four pieces) of news"),
    ("v.使……留下深刻印象", "impress"),
    ("adj.令人印象深刻的", "impressive"),
    ("n.印象", "impression"),
    ("给某人留下深刻印象", "(make/leave) a deep impression on sb."),
    ("身体不好的老人", "old people in poor health"),
    ("v.落下(过去式-过去分词)", "drop-dropped-dropped"),
    ("落下了钱包", "drop the wallet"),
    ("顺便拜访", "drop by")
]