word_list=[
    ("在突发事件中施以援手", "help in an emergency"),
    ("n.紧急情况-复数", "emergency-emergencies"),
    ("在紧急情况下", "in an emergency"),
    ("善举", "acts of kindness"),
    ("adj.善良的 n.种类", "kind"),
    ("n.善良", "kindness"),
    ("adv.和蔼地", "kindly"),
    ("像往常一样，照例", "as usual"),
    ("adj.通常的", "usual"),
    ("adj.不寻常的", "unusual"),
    ("adv.通常，经常", "usually"),
    ("（不）寻常的一天", "a usual day/an unusual day"),
    ("读报纸给他的老邻居听", "read a newspaper to his old neighbour"),
    ("adv.突然", "suddenly"),
    ("adj.突然的/n.", "sudden"),
    ("突然间", "all of a sudden/in a sudden"),
    ("大声呼喊", "cry out"),
    ("心脏病发作", "have a heart attack"),
    ("n./v.发作，侵袭，攻击", "attack"),
    ("用微弱的声音说", "say in a weak voice"),
    ("变得苍白", "turn pale"),
    ("出了一身冷汗", "break out in a cold sweat"),
    ("突然发生某种情况", "break out in"),
    ("n./v.汗/出汗", "sweat"),
    ("n.毛衣", "sweater"),
    ("一阵冷汗", "a cold sweat"),
    ("一阵紧张的汗", "a nervous sweat"),
    ("一阵大汗", "a heavy sweat"),
    ("v.使震惊", "shock"),
    ("adj.感到震惊的/令人震惊的", "shocked/shocking"),
    ("令人震惊的消息", "shocking news"),
    ("深呼吸几次", "take a few deep breaths"),
    ("v.呼吸", "breathe"),
    ("n.呼吸", "breath"),
    ("深呼吸", "take a deep breath"),
    ("屏住呼吸", "hold one's breath"),
    ("上气不接下气", "be out of breath"),
    ("向某人求助", "turn to sb. for help"),
    ("v.操作，动手术", "operate"),
    ("n.接线员，操作员", "operator"),
    ("n.操作，手术", "operation"),
    ("给某人动手术", "operate on sb."),
    ("告诉他贝尔女士住在哪里以及发生了什么", "tell him where Mrs Bell lives and what has happened"),
    ("吃药丸", "take the pills"),
    ("吃药（不可数）", "take medicine"),
    ("吃药片", "take tablets"),
    ("服用胶囊", "take capsules"),
    ("给某人急救", "give sb. first aid"),
    ("n.帮助，援助", "aid"),
    ("立刻，马上", "at once/immediately/right now/right away"),
    ("(离开A)动身去B", "leave (A) for B"),
    ("似乎理解了她的意思", "seem to understand what she means"),
    ("胸痛病例/事件", "cases of chest pain"),
    ("年近七十", "in one's late sixties"),
    ("五十出头", "in one's early fifties"),
    ("在某人四十多岁时", "in one's forties"),
    ("adv.大概，通常", "generally"),
    ("一般来说，通常来说", "generally speaking/in general")
]