word_list = [
("adv. 突然间", "suddenly/all of a sudden/in a sudden"),
("n. 陶土，黏土", "clay"),
("赢得观众的喜爱", "win the audience's favor"),
("adj. 悲伤的", "sad"),
("n. 悲伤", "sadness"),
("v. 使兴奋", "excite"),
("n. 兴奋", "excitement"),
("在做某事前/后/时", "(before/after/when) doing"),
("e.g. 离开前关门", "Close the door (before leaving/before you leave)"),
("到目前为止 → 现在完成时 ", "so far"),
("结果是，证明是", "turn out to be"),
("礼貌地做某事", "do sth. politely/do sth. in a polite way"),
("由……组成", "be made up of"),
("adj. 原味的，原创的", "original"),
("把A和B结合起来", "combine A with B"),
("n. 证书", "certificate"),
("n. 奖牌", "medal"),
("v. 创造", "create"),
("adj. 有创造力的 ", "creative"),
("n. 创造", "creation"),
("n. 创造力", "creativity"),
("不怕慢，单怕站", "It is better late than never."),
("出发", "set (off/out)"),
("建立", "set up"),
("adj. 稳定的", "steady"),
("人生的一课", "a lifetime lesson"),
("一项受欢迎的运动", "a popular sport"),
("一场运动会", "a sports meeting"),
("某人的爱好是做某事", "one's hobby is doing sth."),
("n. 渔夫-复数", "fisherman-fishermen"),
("一整年", "all year (round/around)"),
("限制捕捞", "limit the catch"),
("限制某人做某事", "limit sb. to sth."),
("e.g. 答案限制在两句话内", "You should limit your answer to 2 sentences."),
("e.g. 每天限制自己喝两杯咖啡", "I limit myself to 2 cups of coffee every day."),
("限速", "a speed limit"),
("adj. 有限的", "limited"),
("一生的收获", "catch of a lifetime"),
("住在岛上", "live on an island"),
("在一片湖中央", "in the middle of a lake"),
("系上一个小鱼饵", "tie a small bait"),
("把……系在……上", "tie sb. to sth."),
("把A和B系在一起", "tie A and B together"),
("v. 系 - 过去式 - 过去分词 - 现在分词", "tie-tied-tied-tying"),
("系领带", "wear a tie"),
("练习抛钩", "(practice/practise) casting"),
("南极/北极", "the South/North Pole"),
("在另一个末端", "on the other end"),
("最后，最终", "in the end/finally"),
("在比赛结尾", "at the end of the game"),
("一月底", "at the end of January"),
("在……的末端上", "on the end of"),
("把鱼从水里提起来", "lift the fish from the water"),
("v. 提，拎 - n. 电梯", "lift"),
("搭电梯", "take a lift"),
("让……搭便车", "give sb. a lift"),
("曾经见过（是最高级的标志）", "...have ever (seen/met)..."),
("点燃一根火柴", "light a match"),
("v. 点亮，点燃", "light-(lit/lighted)-(lit/lighted)")
("n. 灯,adj. 轻的/浅色的", "light")
("adj. 重的", "heavy")
("浅蓝色", "light blue")
("深蓝色", "dark blue")
]