word_list = [
("v.禁止-过去式-过去分词", "ban-banned-banned"),
("产生垃圾", "produce waste"),
("对环境有害", "do harm to the environment/be harmful to the environment"),
("adj.必要的、必须的", "necessary"),
("adj.不必要的；多余的，无用的", "unnecessary"),
("n.当地产品", "local products"),
("n.产品", "product"),
("v.生产", "produce"),
("n.生产（过程）", "production"),
("我们应该如何对待野生动物？", "How should we treat wild animals?"),
("n.长颈鹿", "giraffe"),
("n.大猩猩", "gorilla"),
("n.黑猩猩", "chimpanzee"),
("n.美洲豹", "leopard"),
("n.猎豹", "cheetah"),
("n.考拉", "koala"),
("n.鳄鱼", "crocodile"),
("n.朱鹮", "crested ibis"),
("n.蓝鲸", "blue whale"),
("n.袋鼠（复数）", "kangaroo(s)"),
("n.大熊猫", "giant panda"),
("n.非洲象", "African elephant"),
("在电视上看见某物", "see sth. on TV"),
("更多地了解野生动植物", "learn more about wildlife"),
("住在竹林里", "live in the bamboo forests"),
("指材料或整体时不可数，指具体竹子或竹竿时可数", "bamboo-bamboos"),
("华中和华西", "central and western of China"),
("n.中心", "center/centre"),
("adj.中心的", "central"),
("东方的-西方的-南方的-北方的", "eastern-western-southern-northern"),
("最大陆地动物", "the biggest land animal"),
("n.陆地 v.着陆", "land"),
("有很长的象鼻子", "have a long trunk"),
("最大的陆地动物", "the biggest land animal"),
("飞机安全降落在机场。", "The plane landed safely at the airport."),
("n.非洲", "Africa"),
("adj.非洲的 n.非洲人", "African"),
("地球上最大的生物", "the largest living animal on the Earth"),
("住在几乎每一片海洋", "live in almost every ocean"),
("用他们的大尾巴来保持平衡", "use their big tails to keep balance"),
("保持平衡", "keep balance"),
("失去平衡", "lose balance"),
("在学习和休息之间找到一个平衡", "find a balance between study and rest"),
("平衡感", "a sense of balance"),
("平衡A和B（此处balance是动词）", "balance A and B"),
("澳大利亚", "Australia"),
("n.澳大利亚人 adj.澳大利亚的", "Australian"),
("adj.聪明的", "smart"),
("adj.懒惰的-比较级-最高级", "lazy"),
("n. 怠惰，无精打采", "laziness"),
("adj.强壮的", "strong"),
("n.力量", "strength"),
("v.增强", "strengthen"),
("处于危险中", "be in danger"),
("脱离危险", "be out of danger"),
("经过仔细的搜索", "after a careful search"),
("v./n.搜索", "search"),
("n.研究（相当于study）", "research"),
("它长什么样？", "How does it look?/How does it look like?"),
("一只翅膀受伤的天鹅", "a swan with an injured wing"),
("adj.受伤的", "injured"),
("v.使受伤", "injure"),
("n.伤", "injury"),
("宁愿（不）做", "would rather (not) do"),
("adj.饥饿的", "hungry"),
("n.饥饿", "hunger"),
("挨饿", "go hungry"),
("在南极", "in the Antarctic"),
("在北极", "in the Arctic"),
("保护他们自己抵御寒风凛冽的天气", "protect themselves against the cold and windy weather"),
("n.生物", "creature"),
("adj.有魅力的", "charming"),
("adj.强有力的", "mighty"),
("上海大剧院", "Shanghai Grand Theatre"),
("adj.优美的，优雅的", "graceful")
]