word_list = [
    ("在某人二十多岁时", "in one's twenties"),
    ("在20世纪", "in the twentieth century"),
    ("adj. 流利的", "fluent"),
    ("adv. 流利地", "fluently"),
    ("n. 流利", "fluency"),
    ("v.（铃/警报等）突然响起", "go off"),
    ("令某人非常高兴/高兴/尴尬/惊讶/兴奋的是", "much to one's (pleasure/joy/embarrassment/surprise/excitement)"),
    ("adj. 非凡的", "extraordinary"),
    ("n. 磁场", "magnetic field"),
    ("n. 商人", "merchant"),
    ("v. 拓宽某人的视野", "(expand/broaden) one's horizon"),
    ("与某人相处得好/某事进展得好", "get along well with (sb./sth.)"),
    ("v. 编故事", "make up a story"),
    ("v. 上交手机", "hand in the mobile phone"),
    ("v. 上交", "hand in"), 
    ("v. 分发", "hand out"),
    ("v. 变化；n. 零钱（不可数）", "change"),
    ("v. 说一个善意的谎言", "tell a white lie"),
    ("v. 打碎一个有价值的花瓶", "break a valuable vase"),
    ("n./v. 价值；给……定价", "value"),
    ("adj. 值钱的", "valuable"),
    ("v. 划坏；抓伤", "scratch"),
    ("诚信比一个花瓶更珍贵", "Honesty is more precious than a vase."),
    ("adj. 珍贵的", "precious"),
    ("一个诚实的男孩", "an honest boy"),
    ("prep. 根据给出的部分", "according to the given part"),
    ("v. 发生", "take place/happen"),
    ("在山脚下", "at the foot of a mountain"),
    ("一个当地男孩", "a local boy"),
    ("v. 为了钱骗我们", "cheat us for the money"),
    ("为了某物欺骗某人", "cheat sb. for sth."),
    ("骗某人某物", "cheat sb. (out) of sth."),
    ("骗某人去做某事", "cheat sb. into doing sth."),
    ("含泪说出真相", "tell the truth in tears"),
    ("哭泣；泪流满面", "in tears"),
    ("v. 突然哭起来", "burst into tears"),
    ("喜极而泣", "cry tears of joy"),
    ("v./n. 说谎；谎言", "lie"),
    ("n. 说谎者；骗子", "liar"),
    ("v. 惩罚", "punish"),
    ("n. 惩罚", "punishment")
]